/**
 * Demo provider snapshots for visual proof/comparison screenshots.
 *
 * These mimic realistic usage data across multiple providers so the tray
 * panel can be compared against a fully-populated macOS CodexBar panel.
 * Only used when `VITE_DEMO_PROVIDERS=1` is set at build time.
 */
import type { ProviderUsageSnapshot, RateWindowSnapshot } from "../types/bridge";

export const DEMO_ENABLED = import.meta.env.VITE_DEMO_PROVIDERS === "1";

const now = new Date().toISOString();

function demoProviderLimit(): number | null {
  const raw = import.meta.env.VITE_DEMO_PROVIDER_LIMIT;
  if (raw == null || raw === "") return null;
  const parsed = Number(raw);
  if (!Number.isFinite(parsed) || parsed <= 0) return null;
  return Math.floor(parsed);
}

function makeGridProvider(id: string, name: string, usedPct: number): ProviderUsageSnapshot {
  return {
    providerId: id,
    displayName: name,
    primaryLabel: "Monthly",
    primary: {
      usedPercent: usedPct,
      remainingPercent: 100 - usedPct,
      windowMinutes: null,
      resetsAt: null,
      resetDescription: `${Math.floor(Math.random() * 28 + 1)}d`,
      isExhausted: false,
      reservePercent: null,
      reserveDescription: null,
    },
    secondary: null,
    modelSpecific: null,
    tertiary: null,
    extraRateWindows: [],
    cost: null,
    planName: "Free",
    accountEmail: null,
    sourceLabel: "CLI",
    updatedAt: now,
    error: null,
    pace: null,
    accountOrganization: null,
    trayStatusLabel: null,
  };
}

const ALL_DEMO_PROVIDERS: ProviderUsageSnapshot[] = [
  // ── Featured providers (full card data) ──
  {
    providerId: "codex",
    displayName: "Codex",
    primaryLabel: "Session",
    primary: {
      usedPercent: 0,
      remainingPercent: 100,
      windowMinutes: 300,
      resetsAt: null,
      resetDescription: "5h",
      isExhausted: false,
      reservePercent: null,
      reserveDescription: null,
    },
    secondaryLabel: "Weekly",
    secondary: {
      usedPercent: 59,
      remainingPercent: 41,
      windowMinutes: null,
      resetsAt: null,
      resetDescription: "12h 41m",
      isExhausted: false,
      reservePercent: 33,
      reserveDescription: "Lasts until reset",
    },
    modelSpecific: null,
    tertiary: null,
    extraRateWindows: [],
    cost: null,
    planName: "Team",
    accountEmail: "demo.user@example.com",
    sourceLabel: "CLI",
    updatedAt: now,
    error: null,
    pace: null,
    accountOrganization: null,
    trayStatusLabel: null,
  },
  {
    providerId: "claude",
    displayName: "Claude",
    primaryLabel: "Session",
    primary: {
      usedPercent: 72,
      remainingPercent: 28,
      windowMinutes: 300,
      resetsAt: null,
      resetDescription: "1h 23m",
      isExhausted: false,
      reservePercent: null,
      reserveDescription: null,
    },
    secondaryLabel: "Weekly",
    secondary: {
      usedPercent: 45,
      remainingPercent: 55,
      windowMinutes: null,
      resetsAt: null,
      resetDescription: "4d 12h",
      isExhausted: false,
      reservePercent: 33,
      reserveDescription: "Lasts until reset",
    },
    modelSpecific: null,
    tertiary: null,
    extraRateWindows: [],
    cost: null,
    planName: "Pro",
    accountEmail: null,
    sourceLabel: "Cookie",
    updatedAt: now,
    error: null,
    pace: null,
    accountOrganization: null,
    trayStatusLabel: null,
  },
  {
    providerId: "antigravity",
    displayName: "Antigravity",
    primaryLabel: "Session",
    primary: {
      usedPercent: 100,
      remainingPercent: 0,
      windowMinutes: 300,
      resetsAt: null,
      resetDescription: "12m",
      isExhausted: true,
      reservePercent: null,
      reserveDescription: null,
    },
    secondary: null,
    modelSpecific: null,
    tertiary: null,
    extraRateWindows: [],
    cost: null,
    planName: "Team",
    accountEmail: null,
    sourceLabel: "CLI",
    updatedAt: now,
    error: null,
    pace: null,
    accountOrganization: "steipete",
    trayStatusLabel: "Exhausted",
  },
  {
    providerId: "copilot",
    displayName: "GitHub Copilot",
    primaryLabel: "Monthly",
    primary: {
      usedPercent: 89,
      remainingPercent: 11,
      windowMinutes: null,
      resetsAt: null,
      resetDescription: "2d 5h",
      isExhausted: false,
      reservePercent: null,
      reserveDescription: null,
    },
    secondary: null,
    modelSpecific: null,
    tertiary: null,
    extraRateWindows: [],
    cost: null,
    planName: "Business",
    accountEmail: null,
    sourceLabel: "OAuth",
    updatedAt: now,
    error: null,
    pace: null,
    accountOrganization: "steipete",
    trayStatusLabel: null,
  },
  // ── Grid-only providers (fill out icon grid like macOS) ──
  makeGridProvider("cursor", "Cursor", 24),
  makeGridProvider("factory", "Factory", 31),
  makeGridProvider("gemini", "Gemini", 35),
  makeGridProvider("zai", "z.ai", 50),
  makeGridProvider("minimax", "MiniMax", 73),
  makeGridProvider("kiro", "Kiro", 5),
  makeGridProvider("vertexai", "Vertex AI", 38),
  makeGridProvider("augment", "Augment", 55),
  makeGridProvider("opencode", "OpenCode", 15),
  makeGridProvider("kimi", "Kimi", 18),
  makeGridProvider("kimik2", "Kimi K2", 44),
  makeGridProvider("amp", "Amp", 67),
  makeGridProvider("warp", "Warp", 48),
  makeGridProvider("ollama", "Ollama", 3),
  makeGridProvider("azureopenai", "Azure OpenAI", 42),
  makeGridProvider("t3chat", "T3 Chat", 28),
  makeGridProvider("openrouter", "OpenRouter", 68),
  makeGridProvider("synthetic", "Synthetic", 64),
  makeGridProvider("jetbrains", "JetBrains AI", 12),
  makeGridProvider("alibaba", "Alibaba", 8),
  makeGridProvider("alibabatokenplan", "Alibaba Token Plan", 52),
  makeGridProvider("nanogpt", "NanoGPT", 41),
  makeGridProvider("infini", "Infini", 47),
  makeGridProvider("perplexity", "Perplexity", 20),
  makeGridProvider("abacus", "Abacus AI", 57),
  makeGridProvider("mistral", "Mistral", 61),
  makeGridProvider("opencodego", "OpenCode Go", 26),
  makeGridProvider("kilo", "Kilo", 29),
  makeGridProvider("bedrock", "AWS Bedrock", 36),
  makeGridProvider("codebuff", "Codebuff", 59),
  makeGridProvider("deepseek", "DeepSeek", 33),
  makeGridProvider("windsurf", "Windsurf", 39),
  makeGridProvider("manus", "Manus", 46),
  makeGridProvider("mimo", "Xiaomi MiMo", 54),
  makeGridProvider("doubao", "Doubao", 49),
  makeGridProvider("commandcode", "Command Code", 63),
  makeGridProvider("crof", "Crof", 58),
  makeGridProvider("stepfun", "StepFun", 66),
  makeGridProvider("venice", "Venice", 72),
  makeGridProvider("openaiapi", "OpenAI API", 42),
  makeGridProvider("grok", "Grok", 70),
  makeGridProvider("elevenlabs", "ElevenLabs", 43),
  makeGridProvider("deepgram", "Deepgram", 51),
  makeGridProvider("groq", "Groq", 74),
  makeGridProvider("llmproxy", "LLM Proxy", 37),
];

const limit = demoProviderLimit();
export const DEMO_PROVIDERS: ProviderUsageSnapshot[] =
  limit == null ? ALL_DEMO_PROVIDERS : ALL_DEMO_PROVIDERS.slice(0, limit);
