export const TEST_PROVIDER_CATALOG: Array<[string, string]> = [
  ["codex", "Codex"],
  ["claude", "Claude"],
  ["cursor", "Cursor"],
  ["factory", "Factory"],
  ["gemini", "Gemini"],
  ["antigravity", "Antigravity"],
  ["copilot", "Copilot"],
  ["zai", "z.ai"],
  ["minimax", "MiniMax"],
  ["kiro", "Kiro"],
  ["vertexai", "Vertex AI"],
  ["augment", "Augment"],
  ["opencode", "OpenCode"],
  ["kimi", "Kimi"],
  ["kimik2", "Kimi K2"],
  ["amp", "Amp"],
  ["warp", "Warp"],
  ["ollama", "Ollama"],
  ["azureopenai", "Azure OpenAI"],
  ["t3chat", "T3 Chat"],
  ["openrouter", "OpenRouter"],
  ["synthetic", "Synthetic"],
  ["jetbrains", "JetBrains AI"],
  ["alibaba", "Alibaba"],
  ["alibabatokenplan", "Alibaba Token Plan"],
  ["nanogpt", "NanoGPT"],
  ["infini", "Infini"],
  ["perplexity", "Perplexity"],
  ["abacus", "Abacus AI"],
  ["mistral", "Mistral"],
  ["opencodego", "OpenCode Go"],
  ["kilo", "Kilo"],
  ["bedrock", "AWS Bedrock"],
  ["codebuff", "Codebuff"],
  ["deepseek", "DeepSeek"],
  ["windsurf", "Windsurf"],
  ["manus", "Manus"],
  ["mimo", "Xiaomi MiMo"],
  ["doubao", "Doubao"],
  ["commandcode", "Command Code"],
  ["crof", "Crof"],
  ["stepfun", "StepFun"],
  ["venice", "Venice"],
  ["openaiapi", "OpenAI API"],
  ["grok", "Grok"],
  ["elevenlabs", "ElevenLabs"],
  ["deepgram", "Deepgram"],
  ["groq", "Groq"],
  ["llmproxy", "LLM Proxy"],
];
